# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bee.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbee.proto\"]\n\x0cquery_header\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x12\n\nuser_agent\x18\x02 \x01(\t\x12\x15\n\rauthorization\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\":\n\x0bquery_proto\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.query_header\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"4\n\x0creply_header\x12\x0e\n\x06server\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\"_\n\x0breply_proto\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x13\n\x0bstatus_text\x18\x02 \x01(\t\x12\x1d\n\x06header\x18\x03 \x01(\x0b\x32\r.reply_header\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bee_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERY_HEADER._serialized_start=13
  _QUERY_HEADER._serialized_end=106
  _QUERY_PROTO._serialized_start=108
  _QUERY_PROTO._serialized_end=166
  _REPLY_HEADER._serialized_start=168
  _REPLY_HEADER._serialized_end=220
  _REPLY_PROTO._serialized_start=222
  _REPLY_PROTO._serialized_end=317
# @@protoc_insertion_point(module_scope)
